---
- name: "Provision MySQL stack"
  hosts: stack
  connection: local
  tasks:
    - os_stack:
        name: "{{ stack_name }}"
        state: present
        template: heat/mysql_stack.yaml
        environment:
          - heat/mysql_env.yaml
        parameters:
          node_count: "{{ node_count }}"
          image: "{{ image }}"
          flavor: "{{ flavor }}"
          key_name: "{{ key_name }}"
          mysql_network: "{{ mysql_network }}"
          mysql_security_group: "{{ security_group }}"
          mysql_volume_size: "{{ data_volume_size }}"
      register: mysql_stack

- name: "Debug mysql_stack"
  hosts: stack
  connection: local
  tasks:
    - debug:
        var: mysql_stack
    
    - name: Get Facts
      os_server_facts:
        server: "{{ stack_name }}*"

    - name: display server name
      debug:
        msg: "hostname: {{ item.name }} | IP: {{ item.private_v4 }}" 
      with_items: "{{ openstack_servers|json_query('[*]') }}"

    - name: Generate dynamic inventory
      add_host: 
        hostname: "{{ item.name }}"
        groups: mysql
        ansible_host: "{{ item.private_v4 }}"
        ansible_user: "cloud-user"
        ansible_ssh_private_key_file: "/home/centos/.ssh/ine.pem"
      with_items: "{{ openstack_servers|json_query('[*]') }}"

- name: List inventory
  hosts: mysql
  tasks:    
    - name: List inventory
      debug:
        msg: "Hostname is {{ inventory_hostname }} and host ip is {{ ansible_host }}"